# Generated by Django 5.0.4 on 2024-11-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chapter_remarks_alter_chapter_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
