# Generated by Django 5.1.3 on 2024-11-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentcourseenrollment'),
        ('main', '0009_teacher_detail'),
    ]

    operations = [
    ]
