# Generated by Django 5.0.4 on 2024-11-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20241127_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='remarks',
            field=models.CharField(default='No remarks', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='techs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(default='No details provided'),
        ),
    ]
