# Generated by Django 5.0.4 on 2024-11-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_teacher_detail_teacher_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teach_imgs/'),
        ),
    ]
