# Generated by Django 5.0.4 on 2024-12-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_otp_digit_student_verify_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
    ]
